tabs:
    fields:

        ####################################################
        # General
        ####################################################

        general_section:
            tab: General
            label: General
            type: section
        company_name:
            tab: General
            label: Company name
            type: text
        favicon:
            tab: General
            label: Favicon
            type: mediafinder
            mode: image

        ####################################################
        # Colors
        ####################################################

        # General colors section
        colors_general_section:
            tab: Colors
            label: General
            type: section
        primary_color:
            tab: Colors
            label: Primary color
            type: colorpicker
            default: '#376FAD'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'primary-color'
        secondary_color:
            tab: Colors
            label: Secondary color
            type: colorpicker
            default: '#F09125'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'secondary-color'
        link_color:
            tab: Colors
            label: Link color
            type: colorpicker
            default: '#376FAD'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'link-color'
        # Top bar section
        colors_top_section:
            tab: Colors
            label: Top bar
            type: section
        top_text_color:
            tab: Colors
            label: Top bar text color
            type: colorpicker
            default: '#3B3C3D'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'top-text-color'
        top_background_color:
            tab: Colors
            label: Top bar background color
            type: colorpicker
            default: '#FFFFFF'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'top-background-color'
        # Header section
        colors_header_section:
            tab: Colors
            label: Header
            type: section
        header_text_color:
            tab: Colors
            label: Header text color
            type: colorpicker
            default: '#3B3C3D'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'header-text-color'
        header_background_color:
            tab: Colors
            label: Header background color
            type: colorpicker
            default: '#FFFFFF'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'header-background-color'
        # Footer section
        colors_footer_section:
            tab: Colors
            label: Footer
            type: section
        footer_text_color:
            tab: Colors
            label: Footer text color
            type: colorpicker
            default: '#F2F2F2'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'footer-text-color'
        footer_background_color:
            tab: Colors
            label: Footer background color
            type: colorpicker
            default: '#3B3C3D'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'footer-background-color'
        # Copyright section
        colors_copyright_section:
            tab: Colors
            label: Copyright
            type: section
        copyright_text_color:
            tab: Colors
            label: copyright text color
            type: colorpicker
            default: '#F2F2F2'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'copyright-text-color'
        copyright_background_color:
            tab: Colors
            label: Footer background color
            type: colorpicker
            default: '#2C2E2C'
            availableColors: ['#376FAD', '#265E9C', '#F09125', '#2C2E2C', '#3B3C3D', '#F2F2F2', '#FFFFFF']
            assetVar: 'copyright-background-color'

        ####################################################
        # Header
        ####################################################

        header_section:
            tab: Header
            label: Header
            type: section
        header_logo_image:
            tab: Header
            label: Logo
            type: mediafinder
            mode: image
            imageWidth: 300
        header_logo_image_height:
            tab: Header
            label: Logo height
            comment: In pixels
            type: number
            default: 60
        header_logo_text:
            tab: Header
            label: Text
            type: text

        ####################################################
        # Footer
        ####################################################

        footer_section:
            tab: Footer
            label: Footer
            type: section
        footer_title:
            tab: Footer
            label: Title
            type: text
        footer_description:
            tab: Footer
            label: Title
            type: richeditor
            size: small
        contact_form_section:
            tab: Footer
            label: Footer contact form
            type: section
        contact_form_title:
            tab: Footer
            label: Contact form title
            type: text
        footer_rounded_button:
            tab: Footer
            label: Rounded button in footer contact form
            type: switch

        ####################################################
        # Social media
        ####################################################

        social_media_section:
            tab: Social media
            label: Social media
            type: section

        social_media:
            tab: Social media
            prompt: Add social media
            type: repeater
            form:
                fields:
                    name:
                        label: Name
                        type: text
                    icon:
                        label: Icon
                        comment: https://themify.me/themify-icons
                        type: text
                        span: left
                    link:
                        label: Link
                        type: text
                        span: right

        ####################################################
        # Quick contact
        ####################################################

        quick_contact_section:
            tab: Quick contact
            label: Quick contact
            type: section
        quick_contact_title:
            tab: Quick contact
            label: Title
            type: text
        quick_contact_address_company_full_name:
            tab: Quick contact
            label: Company full nane
            type: text
            span: left
        quick_contact_address_street:
            tab: Quick contact
            label: Street
            type: text
            span: right
        quick_contact_address_city:
            tab: Quick contact
            label: City
            type: text
            span: left
        quick_contact_address_zip:
            tab: Quick contact
            label: ZIP code
            type: text
            span: right
        quick_contact_email:
            tab: Quick contact
            label: E-mail
            type: email
            span: left
        quick_contact_phone:
            tab: Quick contact
            label: Phone
            type: text
            span: right

        ####################################################
        # Google Maps API
        ####################################################

        gmap_section:
            tab: Google Maps API
            label: Google Maps API
            type: section
        gmap_api_key:
            tab: Google Maps API
            label: API key
            type: text